source "https://rubygems.org"

# Specify your gem's dependencies in ruby_fundamentals.gemspec

gem "require_all", "~> 3.0"
gem "colorize", "~> 0.8.1"
gem "pry", "~> 0.14.1"

group :development do 
end


gem "activesupport", "~> 6.1"
